/**
 * All available actions for state management.
 */
export enum ActionTypes {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  EXPIRE_TOKEN = 'EXPIRE_TOKEN',
  OPEN_TOAST = 'OPEN_TOAST',
  CLOSE_TOAST = 'CLOSE_TOAST',
  GET_COUNTRIES = 'GET_COUNTRIES',
  GET_CATEGORIES = 'GET_CATEGORIES',
  GET_DISCIPLINES = 'GET_DISCIPLINES',
  ADD_SHOOTER = 'ADD_SHOOTER',
  RESET_SHOOTER = 'RESET_SHOOTER',
}
